name: exercise2_mad9135
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  envify: any
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  envify_generator: any
  build_runner: ^2.0.0

executables:
  exercise2_mad9135: bin/main.dart
